import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const entries = readdirSync(root, { withFileTypes: true });
const documentationRoots = entries.filter((entry) => entry.isDirectory() && ["docs", ".docs"].includes(entry.name)).map((entry) => entry.name);
const required = [
  "AGENTS.md",
  "README.md",
  "package.json",
  "index.html",
  "src/main.ts",
  "src/core/model.ts",
  "docs/Omni_3.32.0.md",
  "docs/Omnevum-MPES-v0.12.0-converged.md",
  "docs/control/control-manifest.json",
  "docs/control/requirements.json",
  "docs/control/acceptance-scenarios.json",
  "docs/control/dependency-sbom.json",
  "docs/control/phase0-acceptance.json",
  "docs/control/mvp-acceptance.json",
  "docs/control/support-matrix.json",
  "docs/control/owner-registry.json",
  "docs/control/capability-catalogue.json",
  "docs/control/effect-outbox-policy.json",
  "docs/control/credential-key-policy.json",
  "docs/control/capability-coverage.json",
  "docs/control/upstream.json",
  "docs/control/patch-fork-delta.json",
  "docs/control/license-provenance.json",
  "docs/control/currentness-radar.json",
  "docs/control/compatibility-matrix.json",
  "docs/control/risk-threat-register.json",
  "docs/control/migration-register.json",
  "docs/control/release-evidence.json",
  "docs/control/engineering-controller.json",
  "docs/control/completion-ledger.json"
];

const failures = [];
if (documentationRoots.length !== 1 || documentationRoots[0] !== "docs") failures.push(`documentation roots=${documentationRoots.join(",") || "none"}`);
for (const path of required) if (!existsSync(join(root, path))) failures.push(`missing ${path}`);

for (const path of ["docs/control/control-manifest.json", "docs/control/requirements.json", "docs/control/acceptance-scenarios.json"]) {
  if (!existsSync(join(root, path))) continue;
  const value = JSON.parse(readFileSync(join(root, path), "utf8"));
  if (value.generatedBy !== "scripts/generate-control.mjs") failures.push(`unidentified generated file ${path}`);
}

const manifestPath = join(root, "docs/control/control-manifest.json");
if (existsSync(manifestPath)) {
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const listed = new Set([...(manifest.generatedFiles ?? []), ...(manifest.maintainedRegisters ?? [])]);
  for (const entry of readdirSync(join(root, "docs/control"))) {
    if (entry.endsWith(".json") && !listed.has(entry)) failures.push(`unindexed control file docs/control/${entry}`);
  }
  for (const [key, item] of Object.entries(manifest.source ?? {})) {
    if (typeof item !== "object" || item === null || typeof item.path !== "string" || typeof item.sha256 !== "string") {
      failures.push(`invalid source receipt ${key}`);
      continue;
    }
    const sourcePath = join(root, item.path);
    if (!existsSync(sourcePath)) failures.push(`missing source receipt target ${item.path}`);
    else {
      const actual = createHash("sha256").update(readFileSync(sourcePath)).digest("hex");
      if (actual !== item.sha256) failures.push(`stale source hash ${item.path}`);
    }
  }
}

const docsEntries = readdirSync(join(root, "docs"), { withFileTypes: true });
if (docsEntries.some((entry) => entry.isFile() && entry.name.toLowerCase() === "current_state.md")) {
  failures.push("state-bound current_state.md must be generated by a verified receipt path");
}

if (failures.length > 0) {
  console.error(`STRUCTURE_AUDIT_FAIL\n- ${failures.join("\n- ")}`);
  process.exitCode = 1;
} else {
  console.log("STRUCTURE_AUDIT_PASS");
}
